name = "One day hope"
author = "Arix"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5107382c169f9ebb193325b86730c5c570c6a0fb693ea3dd07b1450a9b01faa0"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
