name = "One day hope"
author = "Arix"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11bf9d7e9b1f4920609114c5d4be91103d83504c3e038be7cd5309cce579ed08"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
