name = "One day hope"
author = "Arix"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d166276c33e484e319dbc97945084ac7bfeef90a9eab904dd9172e4a9e523ec8"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
